"""Autoscore package."""

from autoscore.constants import (
    PACKAGE_CONFIG_SCHEMA_VERSION,
    PROJECT_MANIFEST_SCHEMA_VERSION,
    SCHEMA_VERSION,
    TASK_ENVELOPE_SCHEMA_VERSION,
    TASK_REQUIREMENTS_SCHEMA_VERSION,
)

__all__ = [
    "PACKAGE_CONFIG_SCHEMA_VERSION",
    "PROJECT_MANIFEST_SCHEMA_VERSION",
    "SCHEMA_VERSION",
    "TASK_ENVELOPE_SCHEMA_VERSION",
    "TASK_REQUIREMENTS_SCHEMA_VERSION",
]
